# Generated by Django 4.2.3 on 2023-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ingredients', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('day', models.DateField(help_text='format (yyyy-mm-dd)', verbose_name='Day')),
                ('seats', models.IntegerField(verbose_name='Number of seats')),
                ('comments', models.CharField(max_length=200, verbose_name='Additional information')),
            ],
        ),
    ]
