# Generated by Django 4.2.3 on 2023-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
